# Generated by Django 4.1.2 on 2022-10-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_latitude_alter_profile_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
